language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/simple-phpunit

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
